variable "region"                {}
variable "repo-name"             {}
variable "azs"                   {}
variable "cluster-name"          {}
variable "vpc-name"              {}
variable "subnet-name-private"   {}
variable "subnet-name-public"    {}
variable "igw"                   {}
variable "route"                 {}
variable "eip"                   {}
variable "nat"                   {}
variable "route-table"           {}
variable "sg-name"               {}
variable "ami-image"             {}
variable "instance-type"         {}
variable "keys"                  {}
variable "instance-tag  "        {}
variable "ecs-task-name"         {}
variable "ecs-service-name"      {}
variable "container-name"        {}
variable "alb-name"              {}
variable "alb-target"            {}
variable "cloudwatch-name"       {}