variable "region" {}
variable "azs" {}
variable "cluster-name" {}
variable "vpc-name" {}
variable "subnet-name-private" {}
variable "subnet-name-public" {}
variable "igw" {}
variable "route" {}
variable "eip" {}
variable "nat" {}
variable "route-table" {}
variable "sg-name" {}
variable "ami-image" {}
variable "ecs-instance-type" {}
variable "bastion-instance-type" {}
variable "db-instance-type" {}
variable "keys" {}
variable "ecs-instance-name" {}
variable "ecs-task-name" {}
variable "ecs-service-name" {}
variable "container-name" {}
variable "alb-name" {}
variable "alb-target" {}
variable "cloudwatch-name" {}
variable "generic-image" {}
variable "db-instance-name" {}
variable "jump-instance-name" {}